import { X, TrendingUp, TrendingDown, FileText, CheckCircle, BarChart3, AlertCircle, Calendar, Users, Clock } from 'lucide-react';

interface JustificationKPIModalProps {
  isOpen: boolean;
  onClose: () => void;
  kpiType: 'coverage' | 'approval' | 'clarity';
  data: {
    coverage?: {
      total: number;
      generated: number;
      manual: number;
      percentage: number;
      byVendor: { vendor: string; sections: number; autoGenerated: number }[];
      recentActivity: { date: string; section: string; type: 'auto' | 'manual' }[];
    };
    approval?: {
      total: number;
      unchanged: number;
      edited: number;
      percentage: number;
      editStats: { minor: number; moderate: number; major: number };
      topAccepted: { section: string; vendor: string; score: number }[];
      topEdited: { section: string; vendor: string; changes: number }[];
    };
    clarity?: {
      average: number;
      highest: { section: string; score: number; vendor: string };
      lowest: { section: string; score: number; vendor: string };
      distribution: { range: string; count: number; percentage: number }[];
      readabilityMetrics: { metric: string; value: string; status: 'good' | 'fair' | 'poor' }[];
    };
  };
}

export function JustificationKPIModal({ isOpen, onClose, kpiType, data }: JustificationKPIModalProps) {
  if (!isOpen) return null;

  const renderCoverageContent = () => {
    const coverageData = data.coverage;
    if (!coverageData) return null;

    return (
      <div className="space-y-6">
        <div className="grid grid-cols-3 gap-4">
          <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-2">
              <FileText className="w-4 h-4 text-emerald-600" />
              <span className="text-xs font-medium text-emerald-900">Total Sections</span>
            </div>
            <p className="text-2xl font-bold text-emerald-900">{coverageData.total}</p>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-2">
              <CheckCircle className="w-4 h-4 text-blue-600" />
              <span className="text-xs font-medium text-blue-900">Auto-Generated</span>
            </div>
            <p className="text-2xl font-bold text-blue-900">{coverageData.generated}</p>
            <p className="text-xs text-blue-600 mt-1">{coverageData.percentage.toFixed(0)}% of total</p>
          </div>

          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-2">
              <Users className="w-4 h-4 text-orange-600" />
              <span className="text-xs font-medium text-orange-900">Manual</span>
            </div>
            <p className="text-2xl font-bold text-orange-900">{coverageData.manual}</p>
            <p className="text-xs text-orange-600 mt-1">{((coverageData.manual / coverageData.total) * 100).toFixed(0)}% of total</p>
          </div>
        </div>

        <div>
          <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-gray-600" />
            Coverage by Vendor
          </h4>
          <div className="space-y-2">
            {coverageData.byVendor.map((vendor, idx) => (
              <div key={idx} className="bg-gray-50 border border-gray-200 rounded-lg p-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-medium text-gray-900">{vendor.vendor}</span>
                  <span className="text-xs text-gray-600">{vendor.sections} sections</span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="flex-1 bg-gray-200 rounded-full h-2">
                    <div
                      className="bg-blue-600 rounded-full h-2"
                      style={{ width: `${(vendor.autoGenerated / vendor.sections) * 100}%` }}
                    />
                  </div>
                  <span className="text-xs font-medium text-gray-700">
                    {vendor.autoGenerated}/{vendor.sections}
                  </span>
                </div>
                <p className="text-xs text-gray-500 mt-1">
                  {((vendor.autoGenerated / vendor.sections) * 100).toFixed(0)}% auto-generated
                </p>
              </div>
            ))}
          </div>
        </div>

        <div>
          <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <Clock className="w-4 h-4 text-gray-600" />
            Recent Activity
          </h4>
          <div className="space-y-2 max-h-48 overflow-y-auto">
            {coverageData.recentActivity.map((activity, idx) => (
              <div key={idx} className="flex items-center gap-3 p-2 border border-gray-200 rounded bg-white">
                <Calendar className="w-4 h-4 text-gray-400 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium text-gray-900 truncate">{activity.section}</p>
                  <p className="text-xs text-gray-500">{activity.date}</p>
                </div>
                <span
                  className={`px-2 py-0.5 text-xs font-medium rounded-full ${
                    activity.type === 'auto'
                      ? 'bg-blue-100 text-blue-700'
                      : 'bg-orange-100 text-orange-700'
                  }`}
                >
                  {activity.type === 'auto' ? 'Auto' : 'Manual'}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  const renderApprovalContent = () => {
    const approvalData = data.approval;
    if (!approvalData) return null;

    return (
      <div className="space-y-6">
        <div className="grid grid-cols-3 gap-4">
          <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-2">
              <CheckCircle className="w-4 h-4 text-emerald-600" />
              <span className="text-xs font-medium text-emerald-900">Unchanged</span>
            </div>
            <p className="text-2xl font-bold text-emerald-900">{approvalData.unchanged}</p>
            <p className="text-xs text-emerald-600 mt-1">{approvalData.percentage.toFixed(0)}% approval rate</p>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-2">
              <FileText className="w-4 h-4 text-blue-600" />
              <span className="text-xs font-medium text-blue-900">Total Reviewed</span>
            </div>
            <p className="text-2xl font-bold text-blue-900">{approvalData.total}</p>
          </div>

          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-2">
              <AlertCircle className="w-4 h-4 text-orange-600" />
              <span className="text-xs font-medium text-orange-900">Edited</span>
            </div>
            <p className="text-2xl font-bold text-orange-900">{approvalData.edited}</p>
            <p className="text-xs text-orange-600 mt-1">{((approvalData.edited / approvalData.total) * 100).toFixed(0)}% modified</p>
          </div>
        </div>

        <div>
          <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-gray-600" />
            Edit Distribution
          </h4>
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-green-50 border border-green-200 rounded-lg p-3">
              <p className="text-xs font-medium text-green-900 mb-1">Minor Edits</p>
              <p className="text-xl font-bold text-green-900">{approvalData.editStats.minor}</p>
              <p className="text-xs text-green-600 mt-1">Typos, formatting</p>
            </div>
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3">
              <p className="text-xs font-medium text-yellow-900 mb-1">Moderate Edits</p>
              <p className="text-xl font-bold text-yellow-900">{approvalData.editStats.moderate}</p>
              <p className="text-xs text-yellow-600 mt-1">Sentence restructure</p>
            </div>
            <div className="bg-red-50 border border-red-200 rounded-lg p-3">
              <p className="text-xs font-medium text-red-900 mb-1">Major Edits</p>
              <p className="text-xl font-bold text-red-900">{approvalData.editStats.major}</p>
              <p className="text-xs text-red-600 mt-1">Content rewrite</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-emerald-600" />
              Top Accepted Sections
            </h4>
            <div className="space-y-2">
              {approvalData.topAccepted.map((item, idx) => (
                <div key={idx} className="bg-emerald-50 border border-emerald-200 rounded-lg p-3">
                  <p className="text-xs font-medium text-gray-900">{item.section}</p>
                  <p className="text-xs text-gray-600 mt-1">{item.vendor}</p>
                  <div className="flex items-center gap-2 mt-2">
                    <div className="flex-1 bg-emerald-200 rounded-full h-1.5">
                      <div
                        className="bg-emerald-600 rounded-full h-1.5"
                        style={{ width: `${item.score}%` }}
                      />
                    </div>
                    <span className="text-xs font-medium text-emerald-700">{item.score}%</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div>
            <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
              <TrendingDown className="w-4 h-4 text-orange-600" />
              Most Edited Sections
            </h4>
            <div className="space-y-2">
              {approvalData.topEdited.map((item, idx) => (
                <div key={idx} className="bg-orange-50 border border-orange-200 rounded-lg p-3">
                  <p className="text-xs font-medium text-gray-900">{item.section}</p>
                  <p className="text-xs text-gray-600 mt-1">{item.vendor}</p>
                  <p className="text-xs font-semibold text-orange-700 mt-2">
                    {item.changes} changes made
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderClarityContent = () => {
    const clarityData = data.clarity;
    if (!clarityData) return null;

    return (
      <div className="space-y-6">
        <div className="bg-gradient-to-r from-blue-50 to-blue-100 border border-blue-200 rounded-lg p-6">
          <div className="text-center">
            <p className="text-sm font-medium text-blue-900 mb-2">Average Clarity Score</p>
            <p className="text-5xl font-bold text-blue-900">{clarityData.average.toFixed(1)}</p>
            <p className="text-xs text-blue-600 mt-2">Based on Flesch-Kincaid readability index</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-3">
              <TrendingUp className="w-4 h-4 text-emerald-600" />
              <span className="text-xs font-semibold text-emerald-900">Highest Score</span>
            </div>
            <p className="text-2xl font-bold text-emerald-900 mb-1">{clarityData.highest.score.toFixed(1)}</p>
            <p className="text-xs font-medium text-gray-900">{clarityData.highest.section}</p>
            <p className="text-xs text-gray-600 mt-1">{clarityData.highest.vendor}</p>
          </div>

          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
            <div className="flex items-center gap-2 mb-3">
              <TrendingDown className="w-4 h-4 text-orange-600" />
              <span className="text-xs font-semibold text-orange-900">Lowest Score</span>
            </div>
            <p className="text-2xl font-bold text-orange-900 mb-1">{clarityData.lowest.score.toFixed(1)}</p>
            <p className="text-xs font-medium text-gray-900">{clarityData.lowest.section}</p>
            <p className="text-xs text-gray-600 mt-1">{clarityData.lowest.vendor}</p>
          </div>
        </div>

        <div>
          <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-gray-600" />
            Score Distribution
          </h4>
          <div className="space-y-2">
            {clarityData.distribution.map((dist, idx) => (
              <div key={idx} className="bg-gray-50 border border-gray-200 rounded-lg p-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-medium text-gray-900">{dist.range}</span>
                  <span className="text-xs text-gray-600">{dist.count} sections</span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="flex-1 bg-gray-200 rounded-full h-2">
                    <div
                      className="bg-blue-600 rounded-full h-2"
                      style={{ width: `${dist.percentage}%` }}
                    />
                  </div>
                  <span className="text-xs font-medium text-gray-700">{dist.percentage}%</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div>
          <h4 className="text-sm font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-gray-600" />
            Readability Metrics
          </h4>
          <div className="space-y-2">
            {clarityData.readabilityMetrics.map((metric, idx) => (
              <div key={idx} className="flex items-center justify-between p-3 bg-white border border-gray-200 rounded-lg">
                <span className="text-xs font-medium text-gray-900">{metric.metric}</span>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-gray-900">{metric.value}</span>
                  <span
                    className={`px-2 py-0.5 text-xs font-medium rounded-full ${
                      metric.status === 'good'
                        ? 'bg-emerald-100 text-emerald-700'
                        : metric.status === 'fair'
                        ? 'bg-yellow-100 text-yellow-700'
                        : 'bg-red-100 text-red-700'
                    }`}
                  >
                    {metric.status}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  const getTitle = () => {
    switch (kpiType) {
      case 'coverage':
        return 'Auto-Generation Coverage Details';
      case 'approval':
        return 'Approval Rate Analysis';
      case 'clarity':
        return 'Clarity Score Breakdown';
      default:
        return 'KPI Details';
    }
  };

  const getIcon = () => {
    switch (kpiType) {
      case 'coverage':
        return <FileText className="w-5 h-5 text-blue-600" />;
      case 'approval':
        return <CheckCircle className="w-5 h-5 text-emerald-600" />;
      case 'clarity':
        return <BarChart3 className="w-5 h-5 text-purple-600" />;
      default:
        return null;
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden">
        <div className="bg-gradient-to-r from-gray-50 to-gray-100 border-b border-gray-200 px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              {getIcon()}
              <h3 className="text-lg font-semibold text-gray-900">{getTitle()}</h3>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
            >
              <X className="w-5 h-5 text-gray-600" />
            </button>
          </div>
        </div>

        <div className="p-6 overflow-y-auto max-h-[calc(90vh-80px)]">
          {kpiType === 'coverage' && renderCoverageContent()}
          {kpiType === 'approval' && renderApprovalContent()}
          {kpiType === 'clarity' && renderClarityContent()}
        </div>
      </div>
    </div>
  );
}
