import { X, TrendingUp, TrendingDown, FileText, CheckCircle, BarChart3, AlertCircle, Calendar, Users, Clock } from 'lucide-react';

interface JustificationKPIModalProps {
  isOpen: boolean;
  onClose: () => void;
  kpiType: 'coverage' | 'approval' | 'clarity';
  data: {
    coverage?: {
      total: number;
      generated: number;
      manual: number;
      percentage: number;
      byVendor: { vendor: string; sections: number; autoGenerated: number }[];
      recentActivity: { date: string; section: string; type: 'auto' | 'manual' }[];
    };
    approval?: {
      total: number;
      unchanged: number;
      edited: number;
      percentage: number;
      editStats: { minor: number; moderate: number; major: number };
      topAccepted: { section: string; vendor: string; score: number }[];
      topEdited: { section: string; vendor: string; changes: number }[];
    };
    clarity?: {
      average: number;
      highest: { section: string; score: number; vendor: string };
      lowest: { section: string; score: number; vendor: string };
      distribution: { range: string; count: number; percentage: number }[];
      readabilityMetrics: { metric: string; value: string; status: 'good' | 'fair' | 'poor' }[];
    };
  };
}

export function JustificationKPIModal({ isOpen, onClose, kpiType, data }: JustificationKPIModalProps) {
  if (!isOpen) return null;

  const renderCoverageContent = () => {
    const coverageData = data.coverage;
    if (!coverageData) return null;

    return (
      <div className="space-y-6">
        <div className="grid grid-cols-3 gap-4">
          <div className="relative rounded-xl border-2 border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-teal-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center shadow-inner">
                <FileText className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-emerald-700 uppercase tracking-wider">Total Sections</span>
            </div>
            <p className="text-3xl font-bold text-emerald-900 mb-1">{coverageData.total}</p>
          </div>

          <div className="relative rounded-xl border-2 border-blue-200 bg-gradient-to-br from-blue-50 via-white to-indigo-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center shadow-inner">
                <CheckCircle className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-blue-700 uppercase tracking-wider">Auto-Generated</span>
            </div>
            <p className="text-3xl font-bold text-blue-900 mb-1">{coverageData.generated}</p>
            <p className="text-xs font-medium text-blue-600 mt-1">{coverageData.percentage.toFixed(0)}% of total</p>
          </div>

          <div className="relative rounded-xl border-2 border-orange-200 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-orange-500 to-amber-500 flex items-center justify-center shadow-inner">
                <Users className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-orange-700 uppercase tracking-wider">Manual</span>
            </div>
            <p className="text-3xl font-bold text-orange-900 mb-1">{coverageData.manual}</p>
            <p className="text-xs font-medium text-orange-600 mt-1">{((coverageData.manual / coverageData.total) * 100).toFixed(0)}% of total</p>
          </div>
        </div>

        <div>
          <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center shadow-inner">
              <BarChart3 className="w-3.5 h-3.5 text-white" />
            </div>
            <span>Coverage by Vendor</span>
          </h4>
          <div className="space-y-3">
            {coverageData.byVendor.map((vendor, idx) => {
              const percentage = (vendor.autoGenerated / vendor.sections) * 100;
              return (
                <div key={idx} className="rounded-xl border-2 border-slate-200 bg-gradient-to-br from-white via-slate-50/30 to-slate-50 p-4 shadow-md hover:shadow-lg transition-all duration-200">
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-sm font-bold text-gray-900">{vendor.vendor}</span>
                    <span className="text-xs font-semibold text-slate-600 bg-slate-100 px-2 py-1 rounded-md">{vendor.sections} sections</span>
                  </div>
                  <div className="flex items-center gap-3 mb-2">
                    <div className="flex-1 bg-gray-200 rounded-full h-3 shadow-inner">
                      <div
                        className="bg-gradient-to-r from-blue-500 to-indigo-600 rounded-full h-3 transition-all duration-300"
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                    <span className="text-xs font-bold text-gray-900 min-w-[50px] text-right">
                      {vendor.autoGenerated}/{vendor.sections}
                    </span>
                  </div>
                  <p className="text-xs font-medium text-blue-600">
                    {percentage.toFixed(0)}% auto-generated
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        <div>
          <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-slate-500 to-slate-600 flex items-center justify-center shadow-inner">
              <Clock className="w-3.5 h-3.5 text-white" />
            </div>
            <span>Recent Activity</span>
          </h4>
          <div className="space-y-2 max-h-48 overflow-y-auto custom-scrollbar pr-2">
            {coverageData.recentActivity.map((activity, idx) => (
              <div key={idx} className="flex items-center gap-3 p-3 rounded-xl border-2 border-slate-200 bg-gradient-to-br from-white via-slate-50/30 to-slate-50 shadow-sm hover:shadow-md transition-all duration-200">
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-slate-400 to-slate-500 flex items-center justify-center shadow-inner flex-shrink-0">
                  <Calendar className="w-4 h-4 text-white" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-semibold text-gray-900 truncate">{activity.section}</p>
                  <p className="text-xs text-gray-600 mt-0.5">{activity.date}</p>
                </div>
                <span
                  className={`px-3 py-1.5 text-xs font-bold rounded-lg border shadow-sm ${
                    activity.type === 'auto'
                      ? 'bg-gradient-to-r from-blue-50 to-indigo-50 text-blue-700 border-blue-200'
                      : 'bg-gradient-to-r from-orange-50 to-amber-50 text-orange-700 border-orange-200'
                  }`}
                >
                  {activity.type === 'auto' ? 'Auto' : 'Manual'}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  const renderApprovalContent = () => {
    const approvalData = data.approval;
    if (!approvalData) return null;

    return (
      <div className="space-y-6">
        <div className="grid grid-cols-3 gap-4">
          <div className="relative rounded-xl border-2 border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-teal-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center shadow-inner">
                <CheckCircle className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-emerald-700 uppercase tracking-wider">Unchanged</span>
            </div>
            <p className="text-3xl font-bold text-emerald-900 mb-1">{approvalData.unchanged}</p>
            <p className="text-xs font-medium text-emerald-600 mt-1">{approvalData.percentage.toFixed(0)}% approval rate</p>
          </div>

          <div className="relative rounded-xl border-2 border-blue-200 bg-gradient-to-br from-blue-50 via-white to-indigo-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center shadow-inner">
                <FileText className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-blue-700 uppercase tracking-wider">Total Reviewed</span>
            </div>
            <p className="text-3xl font-bold text-blue-900">{approvalData.total}</p>
          </div>

          <div className="relative rounded-xl border-2 border-orange-200 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-orange-500 to-amber-500 flex items-center justify-center shadow-inner">
                <AlertCircle className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-orange-700 uppercase tracking-wider">Edited</span>
            </div>
            <p className="text-3xl font-bold text-orange-900 mb-1">{approvalData.edited}</p>
            <p className="text-xs font-medium text-orange-600 mt-1">{((approvalData.edited / approvalData.total) * 100).toFixed(0)}% modified</p>
          </div>
        </div>

        <div>
          <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center shadow-inner">
              <BarChart3 className="w-3.5 h-3.5 text-white" />
            </div>
            <span>Edit Distribution</span>
          </h4>
          <div className="grid grid-cols-3 gap-3">
            <div className="rounded-xl border-2 border-green-200 bg-gradient-to-br from-green-50 via-white to-emerald-50 p-4 shadow-md hover:shadow-lg transition-all duration-200">
              <p className="text-xs font-semibold text-green-700 uppercase tracking-wider mb-2">Minor Edits</p>
              <p className="text-2xl font-bold text-green-900 mb-1">{approvalData.editStats.minor}</p>
              <p className="text-xs text-green-600">Typos, formatting</p>
            </div>
            <div className="rounded-xl border-2 border-yellow-200 bg-gradient-to-br from-yellow-50 via-white to-amber-50 p-4 shadow-md hover:shadow-lg transition-all duration-200">
              <p className="text-xs font-semibold text-yellow-700 uppercase tracking-wider mb-2">Moderate Edits</p>
              <p className="text-2xl font-bold text-yellow-900 mb-1">{approvalData.editStats.moderate}</p>
              <p className="text-xs text-yellow-600">Sentence restructure</p>
            </div>
            <div className="rounded-xl border-2 border-red-200 bg-gradient-to-br from-red-50 via-white to-rose-50 p-4 shadow-md hover:shadow-lg transition-all duration-200">
              <p className="text-xs font-semibold text-red-700 uppercase tracking-wider mb-2">Major Edits</p>
              <p className="text-2xl font-bold text-red-900 mb-1">{approvalData.editStats.major}</p>
              <p className="text-xs text-red-600">Content rewrite</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
              <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center shadow-inner">
                <TrendingUp className="w-3.5 h-3.5 text-white" />
              </div>
              <span>Top Accepted Sections</span>
            </h4>
            <div className="rounded-xl border-2 border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-teal-50 p-4 shadow-md">
              <div className="space-y-3">
                {approvalData.topAccepted.map((item, idx) => (
                  <div key={idx} className="pb-3 border-b border-emerald-200/50 last:border-b-0 last:pb-0">
                    <p className="text-xs font-bold text-gray-900">{item.section}</p>
                    <p className="text-xs text-gray-600 mt-1">{item.vendor}</p>
                    <div className="flex items-center gap-2 mt-3">
                      <div className="flex-1 bg-emerald-200 rounded-full h-2 shadow-inner">
                        <div
                          className="bg-gradient-to-r from-emerald-500 to-teal-600 rounded-full h-2 transition-all duration-300"
                          style={{ width: `${item.score}%` }}
                        />
                      </div>
                      <span className="text-xs font-bold text-emerald-700 min-w-[45px] text-right">{item.score}%</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div>
            <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
              <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-orange-500 to-amber-500 flex items-center justify-center shadow-inner">
                <TrendingDown className="w-3.5 h-3.5 text-white" />
              </div>
              <span>Most Edited Sections</span>
            </h4>
            <div className="space-y-3">
              {approvalData.topEdited.map((item, idx) => (
                <div key={idx} className="rounded-xl border-2 border-orange-200 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-4 shadow-md hover:shadow-lg transition-all duration-200">
                  <p className="text-xs font-bold text-gray-900">{item.section}</p>
                  <p className="text-xs text-gray-600 mt-1">{item.vendor}</p>
                  <p className="text-xs font-bold text-orange-700 mt-3 bg-orange-100 px-2 py-1 rounded-md inline-block">
                    {item.changes} changes made
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  };

  const renderClarityContent = () => {
    const clarityData = data.clarity;
    if (!clarityData) return null;

    return (
      <div className="space-y-6">
        <div className="relative rounded-xl border-2 border-purple-200 bg-gradient-to-br from-purple-50 via-white to-violet-50 p-5 shadow-lg">
          <div className="text-center">
            <p className="text-xs font-semibold text-purple-700 uppercase tracking-wider mb-2">Average Clarity Score</p>
            <p className="text-4xl font-bold bg-gradient-to-r from-purple-600 to-violet-600 bg-clip-text text-transparent mb-1">{clarityData.average.toFixed(1)}</p>
            <p className="text-xs text-purple-600 font-medium">Based on Flesch-Kincaid readability index</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="rounded-xl border-2 border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-teal-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center shadow-inner">
                <TrendingUp className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-emerald-700 uppercase tracking-wider">Highest Score</span>
            </div>
            <p className="text-3xl font-bold text-emerald-900 mb-2">{clarityData.highest.score.toFixed(1)}</p>
            <p className="text-xs font-bold text-gray-900">{clarityData.highest.section}</p>
            <p className="text-xs text-gray-600 mt-1">{clarityData.highest.vendor}</p>
          </div>

          <div className="rounded-xl border-2 border-orange-200 bg-gradient-to-br from-orange-50 via-white to-amber-50 p-5 shadow-md hover:shadow-lg transition-all duration-200">
            <div className="flex items-center gap-2 mb-3">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-orange-500 to-amber-500 flex items-center justify-center shadow-inner">
                <TrendingDown className="w-4 h-4 text-white" />
              </div>
              <span className="text-xs font-semibold text-orange-700 uppercase tracking-wider">Lowest Score</span>
            </div>
            <p className="text-3xl font-bold text-orange-900 mb-2">{clarityData.lowest.score.toFixed(1)}</p>
            <p className="text-xs font-bold text-gray-900">{clarityData.lowest.section}</p>
            <p className="text-xs text-gray-600 mt-1">{clarityData.lowest.vendor}</p>
          </div>
        </div>

        <div>
          <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-purple-500 to-violet-500 flex items-center justify-center shadow-inner">
              <BarChart3 className="w-3.5 h-3.5 text-white" />
            </div>
            <span>Score Distribution</span>
          </h4>
          <div className="space-y-3">
            {clarityData.distribution.map((dist, idx) => (
              <div key={idx} className="rounded-xl border-2 border-slate-200 bg-gradient-to-br from-white via-slate-50/30 to-slate-50 p-4 shadow-md hover:shadow-lg transition-all duration-200">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs font-bold text-gray-900">{dist.range}</span>
                  <span className="text-xs font-semibold text-slate-600 bg-slate-100 px-2 py-1 rounded-md">{dist.count} sections</span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="flex-1 bg-gray-200 rounded-full h-3 shadow-inner">
                    <div
                      className="bg-gradient-to-r from-purple-500 to-violet-600 rounded-full h-3 transition-all duration-300"
                      style={{ width: `${dist.percentage}%` }}
                    />
                  </div>
                  <span className="text-xs font-bold text-gray-900 min-w-[45px] text-right">{dist.percentage}%</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div>
          <h4 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
            <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-slate-500 to-slate-600 flex items-center justify-center shadow-inner">
              <AlertCircle className="w-3.5 h-3.5 text-white" />
            </div>
            <span>Readability Metrics</span>
          </h4>
          <div className="space-y-2">
            {clarityData.readabilityMetrics.map((metric, idx) => (
              <div key={idx} className="flex items-center justify-between p-4 rounded-xl border-2 border-slate-200 bg-gradient-to-br from-white via-slate-50/30 to-slate-50 shadow-sm hover:shadow-md transition-all duration-200">
                <span className="text-xs font-semibold text-gray-900">{metric.metric}</span>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-bold text-gray-900">{metric.value}</span>
                  <span
                    className={`px-3 py-1 text-xs font-bold rounded-lg border shadow-sm ${
                      metric.status === 'good'
                        ? 'bg-gradient-to-r from-emerald-50 to-teal-50 text-emerald-700 border-emerald-200'
                        : metric.status === 'fair'
                        ? 'bg-gradient-to-r from-yellow-50 to-amber-50 text-yellow-700 border-yellow-200'
                        : 'bg-gradient-to-r from-red-50 to-rose-50 text-red-700 border-red-200'
                    }`}
                  >
                    {metric.status}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  const getTitle = () => {
    switch (kpiType) {
      case 'coverage':
        return 'Auto-Generation Coverage Details';
      case 'approval':
        return 'Approval Rate Analysis';
      case 'clarity':
        return 'Clarity Score Breakdown';
      default:
        return 'KPI Details';
    }
  };

  const getIcon = () => {
    switch (kpiType) {
      case 'coverage':
        return (
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-500 flex items-center justify-center shadow-inner">
            <FileText className="w-5 h-5 text-white" />
          </div>
        );
      case 'approval':
        return (
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-500 flex items-center justify-center shadow-inner">
            <CheckCircle className="w-5 h-5 text-white" />
          </div>
        );
      case 'clarity':
        return (
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-violet-500 flex items-center justify-center shadow-inner">
            <BarChart3 className="w-5 h-5 text-white" />
          </div>
        );
      default:
        return null;
    }
  };

  const getHeaderGradient = () => {
    switch (kpiType) {
      case 'coverage':
        return 'from-blue-50 via-white to-indigo-50 border-blue-200';
      case 'approval':
        return 'from-emerald-50 via-white to-teal-50 border-emerald-200';
      case 'clarity':
        return 'from-purple-50 via-white to-violet-50 border-purple-200';
      default:
        return 'from-gray-50 via-white to-slate-50 border-gray-200';
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-[0_25px_50px_rgba(0,0,0,0.25)] max-w-4xl w-full max-h-[90vh] overflow-hidden border-2 border-slate-200">
        <div className={`bg-gradient-to-br ${getHeaderGradient()} border-b-2 px-6 py-5`}>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              {getIcon()}
              <div>
                <h3 className="text-lg font-bold text-gray-900">{getTitle()}</h3>
                <p className="text-xs text-gray-600 mt-0.5">Detailed analysis and insights</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-white/80 rounded-xl transition-all duration-200 hover:scale-110 shadow-sm"
            >
              <X className="w-5 h-5 text-gray-600" />
            </button>
          </div>
        </div>

        <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)] custom-scrollbar">
          {kpiType === 'coverage' && renderCoverageContent()}
          {kpiType === 'approval' && renderApprovalContent()}
          {kpiType === 'clarity' && renderClarityContent()}
        </div>
      </div>
    </div>
  );
}
